# Generated by Django 6.0.3 on 2026-03-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureAccessConfig',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('admin_features', models.JSONField(default=dict)),
                ('intern_features', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feature_access_featureaccessconfig',
                'ordering': ['id'],
            },
        ),
    ]
