# Generated by Django 6.0.3 on 2026-03-19 05:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('business_days', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('sick', 'Sick'), ('vacation', 'Vacation'), ('emergency', 'Emergency'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=500, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaves_leaverequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intern'], name='leaves_intern_idx'), models.Index(fields=['status'], name='leaves_status_idx'), models.Index(fields=['type'], name='leaves_type_idx')],
            },
        ),
    ]
