# Generated by Django 6.0.3 on 2026-03-19 05:14

import apps.dar.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyActivityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.dar.models.dar_upload_to)),
                ('upload_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('missing', 'Missing')], default='missing', max_length=20)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activity_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dar_dailyactivityreport',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['intern'], name='dar_intern_idx'), models.Index(fields=['date'], name='dar_date_idx'), models.Index(fields=['status'], name='dar_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('intern', 'date'), name='dar_unique_intern_date')],
            },
        ),
    ]
