# Generated by Django 6.0.3 on 2026-03-19 04:39

import apps.interns.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InternProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.CharField(max_length=255)),
                ('intern_role', models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Quality Assurance', 'Quality Assurance'), ('Project Manager', 'Project Manager'), ('Business Analyst', 'Business Analyst')], max_length=50, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('required_hours', models.DecimalField(decimal_places=2, default=480.0, max_digits=6)),
                ('rendered_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('start_date', models.DateField()),
                ('birthdate', models.DateField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.interns.models.avatar_upload_to)),
                ('company_account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company_account_password', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment_required', models.BooleanField(default=True)),
                ('assessment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intern_profiles', to='batches.batch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intern_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interns_internprofile',
                'ordering': ['user__name'],
                'indexes': [models.Index(fields=['user'], name='interns_profile_user_idx'), models.Index(fields=['batch'], name='interns_profile_batch_idx'), models.Index(fields=['intern_role'], name='interns_profile_role_idx')],
            },
        ),
        migrations.CreateModel(
            name='InternRegistrationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('school', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('start_date', models.DateField()),
                ('required_hours', models.IntegerField(default=480)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('intern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interns_internregistrationrequest',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='interns_reg_status_idx'), models.Index(fields=['email'], name='interns_reg_email_idx')],
            },
        ),
    ]
