# Generated by Django 6.0.3 on 2026-03-19 04:55

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='assessments.assessment')),
            ],
            options={
                'db_table': 'assessments_assessmentpage',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmentpage')),
            ],
            options={
                'db_table': 'assessments_assessmentquestion',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InternAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments_internattempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['is_published'], name='assessment_published_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentpage',
            index=models.Index(fields=['assessment'], name='assessment_page_assessment_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentpage',
            index=models.Index(fields=['assessment', 'order'], name='assessment_page_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentpage',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='assessments_page_unique_assessment_order'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['page'], name='assessment_question_page_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('page', 'order'), name='assessments_question_unique_page_order'),
        ),
        migrations.AddIndex(
            model_name='internattempt',
            index=models.Index(fields=['intern'], name='attempt_intern_idx'),
        ),
        migrations.AddIndex(
            model_name='internattempt',
            index=models.Index(fields=['assessment'], name='attempt_assessment_idx'),
        ),
        migrations.AddIndex(
            model_name='internattempt',
            index=models.Index(fields=['completed'], name='attempt_completed_idx'),
        ),
        migrations.AddConstraint(
            model_name='internattempt',
            constraint=models.UniqueConstraint(fields=('intern', 'assessment'), name='assessments_attempt_unique_intern_assessment'),
        ),
    ]
