# Generated by Django 6.0.3 on 2026-03-19 06:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('available', 'Available'), ('issued', 'Issued')], default='available', max_length=20)),
                ('accounts', models.CharField(default='', max_length=100)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_laptops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets_laptop',
                'ordering': ['brand', 'serial_no'],
            },
        ),
        migrations.CreateModel(
            name='LaptopIssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('admin_note', models.CharField(blank=True, max_length=500, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptop_issue_reports', to=settings.AUTH_USER_MODEL)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_reports', to='assets.laptop')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_laptop_issue_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assets_laptopissuereport',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='laptop',
            index=models.Index(fields=['status'], name='assets_laptop_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laptop',
            index=models.Index(fields=['assigned_to'], name='assets_laptop_assigned_idx'),
        ),
        migrations.AddIndex(
            model_name='laptopissuereport',
            index=models.Index(fields=['intern'], name='laptop_issue_intern_idx'),
        ),
        migrations.AddIndex(
            model_name='laptopissuereport',
            index=models.Index(fields=['laptop'], name='laptop_issue_laptop_idx'),
        ),
        migrations.AddIndex(
            model_name='laptopissuereport',
            index=models.Index(fields=['status'], name='laptop_issue_status_idx'),
        ),
    ]
