# Generated by Django 6.0.3 on 2026-03-19 05:36

import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('weekend_days', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'calendar_calendarsettings',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'calendar_holiday',
                'ordering': ['date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(choices=[('meeting', 'Meeting'), ('presentation', 'Presentation')], max_length=20)),
                ('description', models.TextField(default='')),
            ],
            options={
                'db_table': 'calendar_calendarevent',
                'ordering': ['date', 'time', 'title'],
                'indexes': [models.Index(fields=['date'], name='calendar_event_date_idx')],
            },
        ),
    ]
