# Generated by Django 6.0.3 on 2026-03-19 05:38

import apps.calendar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarsettings',
            name='weekend_days',
            field=apps.calendar.models.SQLiteCompatibleIntegerArrayField(base_field=models.IntegerField(), default=list),
        ),
    ]
