# Generated by Django 6.0.3 on 2026-03-19 05:05

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('login_time', models.TimeField(blank=True, null=True)),
                ('logout_time', models.TimeField(blank=True, null=True)),
                ('hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent'), ('overtime', 'Overtime'), ('undertime', 'Undertime')], max_length=20)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_attendancerecord',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['intern'], name='attendance_intern_idx'), models.Index(fields=['date'], name='attendance_date_idx'), models.Index(fields=['status'], name='attendance_status_idx'), models.Index(fields=['intern', 'date'], name='attendance_intern_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('intern', 'date'), name='attendance_unique_intern_date')],
            },
        ),
    ]
