# Generated by Django 6.0.3 on 2026-03-19 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('audience', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audience'], name='notifications_audience_idx'), models.Index(fields=['-created_at'], name='notifications_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='notifications.notification')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_read_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_notificationreadstate',
                'ordering': ['-read_at'],
                'constraints': [models.UniqueConstraint(fields=('notification', 'reader'), name='notifications_readstate_unique_notification_reader')],
            },
        ),
    ]
